// export const host = "https://realtime-chat-3qan.onrender.com";
export const host = import.meta.env.VITE_BASE_URL;
// console.log("host",host);
export const loginRoute = `${host}/api/auth/login`;
export const signupRoute = `${host}/api/auth/register`;
export const logoutRoute = `${host}/api/auth/logout`;
export const allUsersRoute = `${host}/api/auth/allusers`;
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const recieveMessageRoute = `${host}/api/messages/getmsg`;
export const setAvatarRoute = `${host}/api/auth/setavatar`;
